name: smart_camera_app
description: A Smart Camera App in Flutter with AI Filters using GetX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Camera
  camera: ^0.12.0+1

  # Image Processing & AI Filters
  image: ^4.1.7

  # ML Kit - Face Detection
  google_mlkit_face_detection: ^0.13.2

  # Gallery Save
  # Permissions
  permission_handler: ^12.0.1

  # Local Storage
  shared_preferences: ^2.2.3

  # Path
  path_provider: ^2.1.3
  path: ^1.9.0

  # UI
  flutter_animate: ^4.5.0
  lottie: ^3.0.0
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"   # white bg for Android adaptive icon
  adaptive_icon_foreground: "assets/logo.png"
